# Generated by Django 3.2.20 on 2023-09-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20230913_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='recipes.tag'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeTag',
        ),
    ]
