# Generated by Django 3.2.20 on 2023-09-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',)},
        ),
    ]
