# Generated by Django 3.2.20 on 2023-09-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_auto_20230918_2154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
