# Generated by Django 3.2.20 on 2023-09-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_auto_20230919_0857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipetag',
            unique_together={('recipe', 'tag')},
        ),
    ]
