# Generated by Django 3.2.20 on 2023-09-17 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230917_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Используйте только буквы.', regex='^[a-zA-Zа-яА-Я]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Используйте только буквы.', regex='^[a-zA-Zа-яА-Я]+$')]),
        ),
    ]
